# Generated by Django 4.2.1 on 2023-05-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0003_add_follow_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='reason',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
